# fly.toml app configuration file generated for fit-discord-bot
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "fit-discord-bot"
primary_region = "sjc"

[build]

[env]
  ENVIRONMENT = "production"
  LOG_LEVEL = "INFO"

[processes]
  app = "python -m src.main"

[[vm]]
  size = "shared-cpu-1x"
  memory = "512mb"
